INSERT INTO airports ([IATA_CODE], [NAME], [FULL_NAME], [TIMEZONE], [COUNTRY_CODE], [COUNTRY]) VALUES
  ('BKK', 'Bangkok', 'Suvarnabhumi Airport', 'Asia/Bangkok', 'TH', 'Thailand'),
  ('BOR', 'Bokeo', 'Bokeo International Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('CAN', 'Guangzhou', 'Guangzhou Baiyun International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('CNX', 'Chiang Mai', 'Chiang Mai International Airport', 'Asia/Bangkok', 'TH', 'Thailand'),
  ('DAD', 'Danang', 'Da Nang International Airport', 'Asia/Ho_Chi_Minh', 'VN', 'Vietnam'),
  ('HAN', 'Hanoi', 'Noi Bai International Airport', 'Asia/Ho_Chi_Minh', 'VN', 'Vietnam'),
  ('ICN', 'Seoul Incheon', 'Incheon International Airport', 'Asia/Seoul', 'KR', 'South Korea'),
  ('KMG', 'Kunming', 'Kunming Changshui International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('KTI', 'Techo', 'Techo International Airport', 'Asia/Phnom_Penh', 'KH', 'Cambodia'),
  ('LPQ', 'Luang Prabang', 'Luang Prabang International Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('LXG', 'Luang Namtha', 'Luang Namtha Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('NEU', 'Sam Neua', 'Sam Neua Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('NNG', 'Nanning', 'Nanning Wuxu International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('PEK', 'Beijing', 'Beijing Capital International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('PKZ', 'Pakse', 'Pakse International Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('PVG', 'Shanghai Pudong', 'Shanghai Pudong International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('SAI', 'Siem Reap Angkor', 'Siem Reap Angkor International Airport', 'Asia/Phnom_Penh', 'KH', 'Cambodia'),
  ('SGN', 'Ho Chi Minh City', 'Tan Son Nhat International Airport', 'Asia/Ho_Chi_Minh', 'VN', 'Vietnam'),
  ('SWA', 'Jieyang Chaoshan', 'Jieyang Chaoshan International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('SZX', 'Shenzhen Baoan', 'Shenzhen Baoan International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('TSN', 'Tianjin Binhai', 'Tianjin Binhai International Airport', 'Asia/Shanghai', 'CN', 'China'),
  ('VTE', 'Vientiane', 'Wattay International Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('XKH', 'Xieng Khouang', 'Xieng Khouang Airport', 'Asia/Vientiane', 'LA', 'Laos'),
  ('ZVK', 'Savannakhet', 'Savannakhet Airport', 'Asia/Vientiane', 'LA', 'Laos');
